<?php

namespace Database\Seeders;

use App\Models\Package;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class DemoPackagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get random user IDs for creator_id
        $userIds = User::pluck('id')->toArray();
        
        if (empty($userIds)) {
            $this->command->error('No users found. Please seed users first.');
            return;
        }

        // Sample image path
        $sampleImagePath = 'packages/umrah-demo.jpg';

        $packages = [
            [
                'name' => 'Umrah Express 7 Days',
                'slug' => Str::slug('Umrah Express 7 Days'),
                'short_description' => 'Quick and affordable Umrah experience for busy pilgrims',
                'description' => 'Experience the spiritual journey of Umrah with our express package. Perfect for those with limited time but unlimited devotion.',
                'detailed_description' => 'This comprehensive 7-day Umrah package includes everything you need for a blessed pilgrimage. We handle all logistics so you can focus on your spiritual journey. Includes visa processing, flights, hotels near Haram, and guided Ziyarat tours.',
                'type' => 'religious',
                'duration' => 7,
                'base_price' => 1500.00,
                'child_price' => 1200.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Express'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Budget Package 10 Days',
                'slug' => Str::slug('Umrah Budget Package 10 Days'),
                'short_description' => 'Affordable Umrah for families on a budget',
                'description' => 'Perform your Umrah pilgrimage without breaking the bank. Our budget package offers comfortable accommodations and essential services.',
                'detailed_description' => 'This economical 10-day Umrah package provides all necessities for a blessed journey. Includes 3-star hotels near Haram, ground transportation, Ziyarat tours of historical Islamic sites, and experienced multilingual guides.',
                'type' => 'religious',
                'duration' => 10,
                'base_price' => 1200.00,
                'child_price' => 950.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Budget'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Premium Luxury 14 Days',
                'slug' => Str::slug('Umrah Premium Luxury 14 Days'),
                'short_description' => 'VIP Umrah experience with 5-star accommodations',
                'description' => 'Experience Umrah in ultimate luxury with our premium package. Enjoy VIP services, 5-star hotels steps from Haram, and exclusive tours.',
                'detailed_description' => 'Our premium 14-day Umrah package offers unparalleled comfort. Stay in 5-star hotels with Haram views, enjoy private VIP transportation, personalized guidance from experienced scholars, exclusive Ziyarat experiences, and gourmet halal dining.',
                'type' => 'religious',
                'duration' => 14,
                'base_price' => 3500.00,
                'child_price' => 2800.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina', 'Jeddah'],
                'categories' => ['Umrah', 'Luxury', 'VIP'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Family Package 12 Days',
                'slug' => Str::slug('Umrah Family Package 12 Days'),
                'short_description' => 'Perfect Umrah package designed for families with children',
                'description' => 'Bring your whole family on this blessed journey. Our family package accommodates all ages with comfortable arrangements and flexible schedules.',
                'detailed_description' => 'This 12-day family-friendly Umrah package includes spacious family rooms, child-friendly meals, flexible prayer schedules, stroller-accessible routes, and dedicated family coordinators. Special rates for children and infants.',
                'type' => 'religious',
                'duration' => 12,
                'base_price' => 1800.00,
                'child_price' => 1200.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Family'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Ramadan Special 15 Days',
                'slug' => Str::slug('Umrah Ramadan Special 15 Days'),
                'short_description' => 'Experience the blessed month of Ramadan in Mecca and Medina',
                'description' => 'Perform Umrah during the most sacred month. Join us for an unforgettable spiritual experience during Ramadan with special Taraweeh prayers.',
                'detailed_description' => 'Our 15-day Ramadan Umrah package offers a unique opportunity to worship in Haramain during the blessed month. Includes Suhoor and Iftar arrangements, proximity to Haram for Taraweeh prayers, and special Laylatul Qadr programs.',
                'type' => 'religious',
                'duration' => 15,
                'base_price' => 2800.00,
                'child_price' => 2200.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Ramadan', 'Special'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Plus Istanbul 10 Days',
                'slug' => Str::slug('Umrah Plus Istanbul 10 Days'),
                'short_description' => 'Combine Umrah with Istanbul city tour',
                'description' => 'Enhance your Umrah journey with a stopover in historic Istanbul. Visit magnificent Ottoman mosques and Islamic heritage sites.',
                'detailed_description' => 'This 10-day package combines Umrah pilgrimage with a cultural tour of Istanbul. Visit the Blue Mosque, Hagia Sophia, Topkapi Palace, and enjoy traditional Turkish hospitality. Perfect blend of worship and culture.',
                'type' => 'religious',
                'duration' => 10,
                'base_price' => 2100.00,
                'child_price' => 1700.00,
                'currency' => 'USD',
                'destinations' => ['Istanbul', 'Mecca', 'Medina'],
                'categories' => ['Umrah', 'Cultural', 'Combined'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah for Seniors 9 Days',
                'slug' => Str::slug('Umrah for Seniors 9 Days'),
                'short_description' => 'Specially designed Umrah package for elderly pilgrims',
                'description' => 'Comfortable Umrah package tailored for senior citizens with special assistance, wheelchair access, and medical support.',
                'detailed_description' => 'Our 9-day senior-friendly Umrah package provides extra care and support. Includes wheelchair services, hotels closest to Haram, elevator access, medical assistance on standby, slower-paced tours, and comfortable transportation.',
                'type' => 'religious',
                'duration' => 9,
                'base_price' => 1900.00,
                'child_price' => 0.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Seniors', 'Accessible'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Group Package 8 Days',
                'slug' => Str::slug('Umrah Group Package 8 Days'),
                'short_description' => 'Discounted Umrah for groups and organizations',
                'description' => 'Bring your community or organization together for Umrah. Special group rates and customizable itinerary available.',
                'detailed_description' => 'This 8-day group Umrah package is ideal for masjid groups, Islamic organizations, or large families. Includes group coordinator, customizable schedules, shared transportation, and significant discounts for groups of 15+.',
                'type' => 'religious',
                'duration' => 8,
                'base_price' => 1350.00,
                'child_price' => 1050.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Group', 'Discount'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah All-Inclusive 12 Days',
                'slug' => Str::slug('Umrah All-Inclusive 12 Days'),
                'short_description' => 'Worry-free Umrah with everything included',
                'description' => 'Everything taken care of from start to finish. Flights, visas, hotels, meals, transportation, and tours all included.',
                'detailed_description' => 'Our 12-day all-inclusive Umrah package covers every detail. Includes round-trip airfare, visa processing, 4-star hotels, all meals, private transportation, Ziyarat tours, SIM cards, and 24/7 support. No hidden costs.',
                'type' => 'religious',
                'duration' => 12,
                'base_price' => 2500.00,
                'child_price' => 2000.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'All-Inclusive'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Women Only 10 Days',
                'slug' => Str::slug('Umrah Women Only 10 Days'),
                'short_description' => 'Exclusive Umrah package for women pilgrims',
                'description' => 'Safe and comfortable Umrah experience exclusively for women. Female guides, coordinators, and mahram arrangements available.',
                'detailed_description' => 'This 10-day women-only Umrah package provides a secure environment with female tour guides, coordinators, and drivers. Special arrangements for women-specific needs, separate group prayers, and mahram coordination if needed.',
                'type' => 'religious',
                'duration' => 10,
                'base_price' => 1750.00,
                'child_price' => 1400.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Women', 'Exclusive'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah First Timer 11 Days',
                'slug' => Str::slug('Umrah First Timer 11 Days'),
                'short_description' => 'Perfect for first-time Umrah pilgrims with complete guidance',
                'description' => 'Your first Umrah made easy. Comprehensive training, step-by-step guidance, and experienced mentors throughout your journey.',
                'detailed_description' => 'This 11-day package is designed for first-time Umrah performers. Includes pre-departure training workshops, detailed manuals, patient guides who explain each ritual, practice sessions, and continuous support throughout.',
                'type' => 'religious',
                'duration' => 11,
                'base_price' => 1650.00,
                'child_price' => 1300.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Beginner', 'Guided'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Plus Dubai 13 Days',
                'slug' => Str::slug('Umrah Plus Dubai 13 Days'),
                'short_description' => 'Umrah package with Dubai city tour extension',
                'description' => 'Complete your Umrah and explore the wonders of Dubai. Visit Burj Khalifa, Dubai Mall, and traditional souks.',
                'detailed_description' => 'This 13-day package combines spiritual Umrah with Dubai tourism. Perform Umrah in Mecca and Medina, then spend 3 days exploring Dubai\'s modern attractions and Islamic heritage sites. Perfect for families wanting variety.',
                'type' => 'religious',
                'duration' => 13,
                'base_price' => 2400.00,
                'child_price' => 1900.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina', 'Dubai'],
                'categories' => ['Umrah', 'Dubai', 'Combined'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Economy 7 Days',
                'slug' => Str::slug('Umrah Economy 7 Days'),
                'short_description' => 'No-frills budget Umrah for the cost-conscious pilgrim',
                'description' => 'Affordable Umrah focusing on essentials. Basic comfortable accommodations with all necessary services.',
                'detailed_description' => 'Our 7-day economy Umrah package provides essential services at the best price. Includes budget-friendly hotels within walking distance of Haram, shared transportation, basic Ziyarat tours, and visa processing.',
                'type' => 'religious',
                'duration' => 7,
                'base_price' => 999.00,
                'child_price' => 799.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Economy', 'Budget'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah VIP Executive 10 Days',
                'slug' => Str::slug('Umrah VIP Executive 10 Days'),
                'short_description' => 'Premium VIP Umrah for business executives',
                'description' => 'Executive-level Umrah package with business-class flights, 5-star hotels, and VIP services throughout.',
                'detailed_description' => 'This 10-day VIP Umrah package caters to executives and professionals. Includes business-class flights, 5-star Haram-facing rooms, private cars, fast-track immigration, VIP lounges, and personal concierge service.',
                'type' => 'religious',
                'duration' => 10,
                'base_price' => 4500.00,
                'child_price' => 3600.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'VIP', 'Executive'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Educational 14 Days',
                'slug' => Str::slug('Umrah Educational 14 Days'),
                'short_description' => 'Umrah with Islamic history and education focus',
                'description' => 'Deep dive into Islamic history while performing Umrah. Includes lectures, historical site visits, and scholarly discussions.',
                'detailed_description' => 'This 14-day educational Umrah package combines pilgrimage with learning. Features daily lectures from scholars, extensive Ziyarat of historical sites with detailed explanations, visits to Islamic libraries, and interactive Q&A sessions.',
                'type' => 'religious',
                'duration' => 14,
                'base_price' => 2200.00,
                'child_price' => 1750.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina', 'Taif'],
                'categories' => ['Umrah', 'Educational', 'Historical'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Honeymoon 12 Days',
                'slug' => Str::slug('Umrah Honeymoon 12 Days'),
                'short_description' => 'Blessed start to married life with Umrah honeymoon',
                'description' => 'Begin your marriage with blessing. Special honeymoon Umrah package for newlyweds with romantic and spiritual experiences.',
                'detailed_description' => 'This 12-day honeymoon Umrah package is perfect for newly married couples. Includes luxury suite accommodations, special halal dining experiences, private transportation, couple-friendly tours, and spiritual guidance for starting your life together.',
                'type' => 'religious',
                'duration' => 12,
                'base_price' => 3200.00,
                'child_price' => 0.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina', 'Jeddah'],
                'categories' => ['Umrah', 'Honeymoon', 'Couple'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Youth Package 9 Days',
                'slug' => Str::slug('Umrah Youth Package 9 Days'),
                'short_description' => 'Energetic Umrah experience for young Muslims',
                'description' => 'Umrah package designed for youth and young adults. Dynamic schedule with youth-focused activities and mentorship.',
                'detailed_description' => 'This 9-day youth Umrah package engages young pilgrims with age-appropriate guidance, youth mentors, interactive learning sessions, networking opportunities, and energetic group activities alongside traditional Umrah rituals.',
                'type' => 'religious',
                'duration' => 9,
                'base_price' => 1400.00,
                'child_price' => 1100.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Youth', 'Students'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Deluxe 15 Days',
                'slug' => Str::slug('Umrah Deluxe 15 Days'),
                'short_description' => 'Extended deluxe Umrah with comprehensive spiritual experience',
                'description' => 'Longest and most comprehensive Umrah package. Ample time for worship, reflection, and exploring Islamic heritage.',
                'detailed_description' => 'Our 15-day deluxe Umrah package allows you to fully immerse yourself in the spiritual atmosphere. Includes 4-star hotels, extended stays in both Holy Cities, multiple Ziyarat tours, daily Islamic lectures, and plenty of personal worship time.',
                'type' => 'religious',
                'duration' => 15,
                'base_price' => 2600.00,
                'child_price' => 2100.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina', 'Jeddah'],
                'categories' => ['Umrah', 'Deluxe', 'Extended'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Winter Special 11 Days',
                'slug' => Str::slug('Umrah Winter Special 11 Days'),
                'short_description' => 'Comfortable Umrah during pleasant winter season',
                'description' => 'Perform Umrah in the mild winter climate. Ideal weather for Tawaf and outdoor religious activities.',
                'detailed_description' => 'This 11-day winter Umrah package takes advantage of the pleasant December-February weather. More comfortable for outdoor rituals, Ziyarat tours, and walking to Haram. Includes seasonal special programs and winter-friendly arrangements.',
                'type' => 'religious',
                'duration' => 11,
                'base_price' => 1700.00,
                'child_price' => 1350.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Seasonal', 'Winter'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Umrah Customizable 10 Days',
                'slug' => Str::slug('Umrah Customizable 10 Days'),
                'short_description' => 'Flexible Umrah package tailored to your preferences',
                'description' => 'Design your own Umrah experience. Choose your hotels, activities, and schedule based on your needs and budget.',
                'detailed_description' => 'This 10-day customizable Umrah package lets you create your perfect pilgrimage. Select from various hotel options, transportation types, Ziyarat tours, dining preferences, and schedule flexibility. Our team works with you to build your ideal package.',
                'type' => 'religious',
                'duration' => 10,
                'base_price' => 1850.00,
                'child_price' => 1450.00,
                'currency' => 'USD',
                'destinations' => ['Mecca', 'Medina'],
                'categories' => ['Umrah', 'Customizable', 'Flexible'],
                'status' => 'active',
                'approval_status' => 'approved',
            ],
        ];

        $this->command->info('Creating 20 Umrah demo packages...');

        foreach ($packages as $index => $packageData) {
            // Assign random creator
            $packageData['creator_id'] = $userIds[array_rand($userIds)];
            
            // Add common fields
            $packageData = array_merge($packageData, [
                'includes_meals' => $index % 2 === 0,
                'includes_accommodation' => true,
                'includes_transport' => true,
                'includes_guide' => $index % 3 === 0,
                'includes_flights' => $index % 2 === 0,
                'includes_activities' => true,
                'free_cancellation' => $index % 4 === 0,
                'instant_confirmation' => $index % 3 === 0,
                'uses_b2b_services' => $index % 5 === 0,
                'hotel_source' => ['platform', 'external', 'mixed'][array_rand(['platform', 'external', 'mixed'])],
                'transport_source' => ['platform', 'external', 'mixed'][array_rand(['platform', 'external', 'mixed'])],
                'flight_source' => ['own', 'platform', 'external'][array_rand(['own', 'platform', 'external'])],
                'is_featured' => $index % 5 === 0,
                'is_premium' => $index % 4 === 0,
                'allow_customization' => $index % 3 === 0,
                'instant_booking' => $index % 2 === 0,
                'requires_deposit' => true,
                'deposit_percentage' => 30.00,
                'min_participants' => rand(1, 2),
                'max_participants' => rand(20, 50),
                'current_bookings' => rand(0, 15),
                'min_booking_days' => rand(15, 45),
                'platform_commission' => 10.00,
                'commission_rate' => 15.00,
                'views_count' => rand(100, 800),
                'bookings_count' => rand(5, 50),
                'average_rating' => rand(42, 50) / 10,
                'reviews_count' => rand(10, 100),
                'available_from' => now()->subDays(60),
                'available_until' => now()->addMonths(12),
                'start_date' => now()->addDays(rand(30, 120)),
                'end_date' => now()->addDays(rand(121, 240)),
                'approved_at' => now()->subDays(rand(1, 45)),
                'approved_by' => $userIds[array_rand($userIds)],
                'inclusions' => [
                    'Return flight tickets',
                    'Saudi Arabia Umrah visa',
                    'Hotel accommodation near Haram',
                    'Ground transportation in Saudi Arabia',
                    'Ziyarat tours (Mecca & Medina)',
                    'Experienced multilingual guide',
                    'Travel insurance',
                    '24/7 customer support',
                ],
                'exclusions' => [
                    'Personal expenses and shopping',
                    'Meals not mentioned in itinerary',
                    'Tips and gratuities',
                    'Optional tours and activities',
                    'Laundry services',
                ],
                'highlights' => [
                    'Hotels within walking distance to Haram',
                    'Expert Umrah guides and scholars',
                    'Comprehensive Ziyarat tours',
                    'Comfortable air-conditioned transport',
                    'Hassle-free visa processing',
                    'Group prayer coordination',
                ],
                'features' => [
                    'IATA certified travel agency',
                    'Experienced Umrah coordinators',
                    'Pre-departure orientation',
                    'Ihram distribution',
                    'SIM card assistance',
                    'Luggage handling support',
                ],
                'tags' => array_slice(
                    ['umrah', 'pilgrimage', 'mecca', 'medina', 'islamic-travel', 'halal', 'spiritual-journey', 'holy-cities'],
                    0,
                    rand(3, 5)
                ),
                'images' => [
                    [
                        'path' => $sampleImagePath,
                        'is_main' => true,
                        'caption' => 'Umrah Package - ' . $packageData['name'],
                        'sizes' => [
                            'thumbnail' => $sampleImagePath,
                            'medium' => $sampleImagePath,
                            'large' => $sampleImagePath,
                            'original' => $sampleImagePath,
                        ]
                    ]
                ],
                'created_at' => now()->subDays(rand(45, 180)),
                'updated_at' => now()->subDays(rand(1, 44)),
            ]);

            Package::create($packageData);
            $this->command->info("✓ Created: {$packageData['name']}");
        }

        $this->command->info('');
        $this->command->info('✅ Successfully created 20 Umrah packages!');
        $this->command->info('📦 Total packages in database: ' . Package::count());
        $this->command->info('');
        $this->command->info('You can now view the packages at: /api/packages');
    }
}
